### ISSUE TITLE
make test is failing

### ISSUE THREAD

**Issue by jigneshjain25** [google/inverting-proxy#99]
**Cmd:** `make test`

**Error in output**
vet: agent/utils/utils_test.go:180:7: undeclared name: bytes
make: *** [Makefile:35: vet] Error 2

After adding an import for `bytes` in utils_test.go, one test is failing

```
--- FAIL: TestReadRequestWithRetries (0.00s)
    utils_test.go:172: Error status while reading "request" from the proxy
2022/07/21 11:57:21 suppressing panic for copyResponse error in test; copy error: io: read/write on closed pipe
FAIL
FAIL	github.com/google/inverting-proxy/agent/utils	0.059s
FAIL
make: *** [Makefile:9: test] Error 1
```

I believe this is a recent regression from the changes in #98.

**Comment by jigneshjain25** [comment]
@swalkowski PTAL.
